security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        reset_password_request:
            pattern: ^/api/request-reset-password
            stateless: true
            security: false

        reset_password:
            pattern: ^/api/reset-password
            stateless: true
            security: false

        main:
            stateless: true
            custom_authenticators:
                - App\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/google-auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-callback, roles: PUBLIC_ACCESS }
        - { path: ^/api/restaurateur/dishes, roles: PUBLIC_ACCESS }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/orders, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/restaurateur, roles: [ROLE_ADMIN] }
        - { path: ^/api/client, roles: [ROLE_CLIENT, ROLE_ADMIN, ROLE_RESTAURATEUR] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/restaurateur/dishes, roles: [ROLE_RESTAURATEUR, ROLE_ADMIN] }
        - { path: ^/api/order, roles: [ROLE_CLIENT, ROLE_ADMIN, ROLE_RESTAURATEUR] }
        - { path: ^/api/user/profile, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/api/admin/users, roles: [ROLE_ADMIN] }
        - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/request-reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }